# App
quarkus.application.name=gamebuilder
quarkus.http.host=127.0.0.1
quarkus.http.port=2157

# Packaging
quarkus.package.jar.enabled=true
quarkus.package.jar.type=uber-jar

# OpenAPI / Swagger UI
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui

# Logging
quarkus.log.level=INFO
quarkus.log.category."com.gamebuilder".level=DEBUG

# Ollama
ollama.host=http://localhost:11434
ollama.api.key=ollama
ollama.model=llama3
ollama.cooldown.ms=5000
ollama.request.cap=2000
ollama.max.user.prompt.length=1000
